name: Linux

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: ${{ matrix.conf.name }} - Build
    runs-on: ${{ matrix.conf.os }}
    strategy:
      fail-fast: false
      matrix:
        conf:
          - { name: "Ubuntu g++", os: ubuntu-latest, compiler: "g++" }

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build library
        env:
          CXX: ${{matrix.conf.compiler}}
        run: |
          g++ include/ShkyeraGrad.hpp --std=c++17

      - name: Build examples
        env:
          CXX: ${{matrix.conf.compiler}}
        run: |
          g++ examples/scalars.cpp -O3 --std=c++17
          ./a.out
          g++ examples/xor.cpp -O3 --std=c++17
          ./a.out
