name: Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: ${{ matrix.conf.name }} - Build
    runs-on: ${{ matrix.conf.os }}
    strategy:
      fail-fast: false
      matrix:
        conf:
          - {
            name: "Ubuntu g++",
            os: ubuntu-latest,
            compiler: "g++"
          }
          - {
            name: "Ubuntu clang++",
            os: ubuntu-latest,
            compiler: "clang++"
          }
            
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build
      env:
        CXX: ${{matrix.conf.compiler}}
      run: |
          g++ include/shkyeraTensorDemo.cpp --std=c++20
          ./a.out
