name: Windows

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: ${{ matrix.conf.name }} - Build
    runs-on: ${{ matrix.conf.os }}
    strategy:
      fail-fast: false
      matrix:
        conf:
          - { name: "Windows g++", os: windows-latest, compiler: "g++" }

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build library
        env:
          CXX: ${{matrix.conf.compiler}}
        run: |
          g++ include/ShkyeraTensor.hpp --std=c++20
      - name: Build examples
        env:
          CXX: ${{matrix.conf.compiler}}
        run: |
          g++ examples/algebra.cpp --std=c++20
          g++ examples/dataset.cpp --std=c++20
      - name: Test
        env:
          CXX: ${{matrix.conf.compiler}}
        run: |
          g++ tests/mainTest.cpp --std=c++20
          ./a.out
