name: Windows

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: ${{ matrix.conf.name }} - Build
    runs-on: ${{ matrix.conf.os }}
    strategy:
      fail-fast: false
      matrix:
        conf:
          - { name: "Windows g++", os: windows-latest, compiler: "g++" }

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build library
        env:
          CXX: ${{matrix.conf.compiler}}
        run: |
          g++ include/ShkyeraTensor.hpp --std=c++17
      - name: Build examples
        env:
          CXX: ${{matrix.conf.compiler}}
        run: |
          g++ examples/scalars.cpp --std=c++17
          g++ examples/xor_nn.cpp --std=c++17
